name: Sync README and images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Copy README
        run: |
          cp -f README.md ${{ runner.temp }}/README.md

      - name: Checkout GitHub Pages branch
        uses: actions/checkout@v3.1.0
        with:
          ref: gh-pages

      - name: Commit and push README
        run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Sync README from main"
          git push
