name: Sync README and images

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/img/*

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy README
        run: |
          cp -f README.md ${{ runner.temp }}/README.md

      - name: Copy images
        run: |
          cp .github/img/ ${{ runner.temp }}/.github/img/

      - name: Checkout GitHub Pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Commit and push README
        run: |
          cp -f ${{ runner.temp }}/README.md .
          cp ${{ runner.temp }}/.github/img/ .github/img/
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git add .github/img/.
          git commit --signoff -m "Sync README and images from main"
          git push
